#!/bin/sh
./test-jit > test.syrec
trap 'rm -f test.syrec' EXIT
SEDSCRIPT=`objdump -m i386:x86-64 -t test.syrec | grep ABS | sed 's#^0*\([^ ]\+\).*\*ABS\* \(.*\)#s/\$0x\1/\2/g;#'`
objdump -m i386:x86-64 -D test.syrec | sed "$SEDSCRIPT"
